services:
    Egor.TestBundle.Controller.DefaultController.egor_test:
        class: Egor\TestBundle\Controller\DefaultController
        arguments: ["%egor_test.limits_%"]
        arguments: ["%egor_test.categories_%"]
        
        