services:
    #Egor.TestBundle.Controller.DefaultController:
     #   class: Egor\TestBundle\Controller\DefaultController
      #  arguments: ["%egor_test.limits%"]
       # arguments: ["%egor_test.categories%"]
        
        